### ISSUE TITLE
Darknet component has a memory leak when running "tiny yolo" jobs on CPU resources

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#1062]
A user identified that the Darknet component process was growing over time. The user was sending video jobs to Darknet with just a handful of frames - most with just 1 frame - from Subsense via `FEED_FORWARD_TYPE=FRAME`. Subsense had `USE_TRACK_MERGING=0` and `USE_PREPROCESSOR=0`, but the track merging system property was set to true.

In general, the core issue does not seem to be related to Subsense.

From @brosenberg42:

> Before running any jobs it was using 33mb. After one job, 86mb. 5 was 111mb. 25 was 610mb. 50 was 1.2gb. 100 was 2.3gb. 200 was 4.7gb. 400 was 9.3gb. 600 was 13.9gb. 1000 was 18.6gb

Land to R4.0.0.

**Comment by brosenberg42** [comment]
This appears to be caused by the Darknet library not properly freeing the network. I had to make some changes to get the Darknet component to only load the network once and re-use it for each job. When I did this, after running the first job it was using 189mb on the 600th job it was using 191mb. As I mentioned, I had to make a few changes to get it to work, so I still need to test just loading and freeing the network by itself to verify. 

We call [`free_network`](https://github.com/openmpf/openmpf-components/blob/master/cpp/DarknetDetection/darknet_lib/src/network.c#L720) to free the network, which then calls [`free_layer`](https://github.com/openmpf/openmpf-components/blob/master/cpp/DarknetDetection/darknet_lib/src/layer.c#L6). The are various pointer fields in the [`layer` struct](https://github.com/openmpf/openmpf-components/blob/master/cpp/DarknetDetection/darknet_lib/include/darknet.h#L124) that are not freed, such as [`counts`](https://github.com/openmpf/openmpf-components/blob/master/cpp/DarknetDetection/darknet_lib/include/darknet.h#L224).
