### ISSUE TITLE
Update to OpenCV 4 to get NVIDIA GPU support for the DNN module

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#1101]
[This guide](https://www.pyimagesearch.com/2020/02/03/how-to-use-opencvs-dnn-module-with-nvidia-gpus-cuda-and-cudnn/) explains that OpenCV 4.2 "now supports NVIDIA GPUs for inference using OpenCV’s dnn module, improving inference speed by up to 1549%".

We should consider upgrading to the latest release of OpenCV if it's not that much extra work. Currently, that's OpenCV 4.3.

Once we update the version of OpenCV, we should simplify the Darknet component to make use of OpenCV DNN rather than compiling the Darknet framework directly. That should result in some [performance improvement](https://www.learnopencv.com/deep-learning-based-object-detection-using-yolov3-with-opencv-python-c/).

**Comment by jrobble** [comment]
@fpertl is currently looking into this.

**Comment by fpertl** [comment]
For reference, I pushed (hopefully correctly) my edits to add openCV4 with cuda and cuDnn to the docker builds of openMPF. The branch(es) are `opencv4-gpu-test`.

Summary:
`Dockerfile.gpu` files for building images using nvidia/cuda:centos7 images 
`CMakeList.txt` use parameterized opencCV version with an ENV.
Code edits were only done in openmpf_cpp_sdk to change names of constants. What else uses openCV in MPF?!

Details:
The build images are pretty large, probably since I compiled opencv4 was compiled with python3 & numpy.  What are your thoughts on  removing opencv from the general builder image and only adding it where needed, is that possible?  That way the cpp components don't get the python stuff added. There may also be better ways to trim down the nvidia/cuda images, but I have not spend time on that, but just pulled them as is.   

Constants:
```
CV_WINDOW_AUTOSIZE      ->  cv::WINDOW_AUTOSIZE
CV_BGR2GRAY             ->  cv::COLOR_BGR2GRAY
CV_FILLED               ->  cv::FILLED
CV_LOAD_IMAGE_IGNORE_ORIENTATION    ->  cv::IMREAD_IGNORE_ORIENTATION
CV_LOAD_IMAGE_COLOR         ->  cv::IMREAD_COLOR
CV_CAP_PROP_FRAME_WIDTH     ->  cv::CAP_PROP_FRAME_WIDTH
CV_CAP_PROP_FRAME_HEIGHT    ->  cv::CAP_PROP_FRAME_HEIGHT
CV_CAP_PROP_FRAME_FPS       ->  cv::CAP_PROP_FRAME_FPS
CV_FOURCC(                  ->  cv::VideoWriter::fourcc(
```
