### ISSUE TITLE
Validate protocol for streaming jobs

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#171]
The uriScheme checks for supported protocols for both batch and stream jobs are done when the Transient objects are created: 

`TransientMedia.setUri()`
`TransientStream.setUri()`

For streaming jobs, we should do this earlier, say in controller classes or the org.mitre.mpf.rest.api classes, so that the job can be rejected sooner.

**Comment by dpierce17** [comment]
Adding support for this in the StreamingJobController and JobController classes, using the following consideration.  

Where streaming jobs only have one stream URI to be checked against the supported protocols, a batch job allows for an array of media.  For streaming jobs, if the stream URI is not one of the supported protocols, the streaming job will be rejected with a streaming job creation (error) response.  

For batch jobs, current behavior is for all media in the batch job to be checked for validity in the DetectionSplitter.  Any media that don't satisfy the URI check will be ignored, and a "Skipping Media" error message will be logged in DetectionSplitter.  We'll be keeping this behavior when the early check for protocol is added to JobController.  

So, just to clarify that a bad streaming URI will cause a streaming job to be rejected.  A bad media URI will be ignored, the batch job will not be rejected.

**Comment by dpierce17** [comment]
Revising this issue so that it only applies to Streaming Jobs, it will not be applied to Batch Jobs.  Reason is, for streaming it makes sense to reject the job right away since there is only one URI.  Batch jobs allow for an array of media URI, so possibly 1-of-N media should be rejected due to a malformed or invalid URI.  We would want to report the bad media in the JSON output, so for this reason we will keep the check of protocol validity (and add a check for file existence and readability) in TransientMedia.setUri.

**Comment by dpierce17** [comment]
Closed, landed in PR #250
