### ISSUE TITLE
openmpf-develop-github-with-pull-request not running gtests

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#283]
The openmpf-develop-github-with-pull-request build should be running gtests.

**Comment by clnowacki** [comment]
The problem is that certain builds set components.build.dir in the "mvn verify" command to ${WORKSPACE}/openmpf. Then the RunGTests script looks for the mpf-component-build directory in ${WORKSPACE}, and doesn't find any tests. This is a problem for more than just the openmpf-develop-github-with-pull-request job.

**Comment by jrobble** [comment]
OBE
