### ISSUE TITLE
Periodically send health reports for streaming jobs

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#338]
Related #297.

Periodically send health reports to the health report callback URI (if one was provided) according to the health report callback rate system property. The streaming job status should be in Redis.

**Comment by dpierce17** [comment]
On our development platform, is there a common way for us to test to see if the callback is received?

**Comment by dpierce17** [comment]
Will be using Spark to test the HealthReportCallbacks.  See OpenMPF issue #354

**Comment by dpierce17** [comment]
Update: Until it is determined otherwise, issuance of an out-of-cycle health report (such as a health report that is sent when a streaming jobs job status changes) will not affect the timing for sending of the next scheduled health report for that job.

**Comment by dpierce17** [comment]
Update: Periodic Health Reports will contain health information for all streaming jobs which register the same HealthReportCallbackURI.  Event based Health Reports (such as a health report sent due to a change in job status) will only contain health information for the streaming job which triggered the event.

**Comment by dpierce17** [comment]
Update: we have to allow for streaming jobs which register the same HealthReportCallbackURI, but register different HTTP methods for that callback (i.e. POST vs. GET)

**Comment by dpierce17** [comment]
landed with PR380
