### ISSUE TITLE
Add handling in WFM for messages received in JobStatus, NewActivity, SummaryReport queues

### ISSUE THREAD

**Issue by dpierce17** [openmpf/openmpf#348]
The streaming component executor will send messages to WFM via queues:
•	Job status queue : for sending STALLED and IN_PROGRESS messages
•	New activity queue : for sending frame id and frame timestamp (system time)
•	Summary report queue (protobuf of video track collection)

**Comment by dpierce17** [comment]
Will all timestamps be in UTC standard time?

**Comment by jrobble** [comment]
Currently OpenMPF uses system time, which is not necessarily UTC.

**Comment by jrobble** [comment]
Note that we’ve moved away from using a DetectionReponse for the segment summary report and are now instead using a [StreamingDetectionReponse](https://github.com/openmpf/openmpf/blob/develop/trunk/protobuf/src/main/proto/detection.proto#L241). @brosenberg42 created a [POJO representation](https://reviewable.io/reviews/openmpf/openmpf/401/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/transients/SegmentSummaryReport.java) for it in his current PR. In the past we planned on the segment summary report taking the same form as the JSON output object. Now it’s slightly different. To account for this, we need to create a JSON representation for the segment summary report in the interop package so that we can return it in the callback.

**Comment by jrobble** [comment]
Note that the POJO representation does not include timestamps for tracks nor timestamps for the individual detections that make up a track. Those need to be included in the summary report JSON that's returned in the callback. 

Consider reusing `JsonDetectionOutputObject`, which has `offsetTime, and `JsonTrackOuputObject`, which has `startOffsetTime` and `stopOffsetTime`.
