### ISSUE TITLE
Add new activity alerts to health report callback

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#350]
Update HealthReportData with:
- activity frame id
- activity timestamp 

Update StreamingJobInfo with:
- activity frame id
- activity timestamp

**Comment by dpierce17** [comment]
all timestamps to be reported using system time, in format: "2017-11-06 14:44:26.0" to be consistent with other timestamps in openmpf

**Comment by dpierce17** [comment]
Question: Simplified Streaming Control Flow v1 shows health report as "Job last activity includes the frame id and time since the job was started".  I'm assuming that Simplified Streaming Control Flow v1 should be changed to say "Job last activity includes the frame id and timestamp of the activity".  Is this correct or do we also want to add streaming job run time to the health report?

**Comment by jrobble** [comment]
You're correct. I just updated the diagram.

**Comment by dpierce17** [comment]
Adding to this task removal of newTrackAlertCallbackUri from the StreamingJobCreationRequest definition

**Comment by dpierce17** [comment]
landed with PR380
