### ISSUE TITLE
Update REST API doc description of StreamingJobCreationRequest stallTimeout

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#488]
Update REST API doc description of StreamingJobCreationRequest stallTimeout to mention that if the value is -1, in additional to never terminating due to a stall, we will not try to reconnect to the stream.

**Comment by dpierce17** [comment]
Ok, I changed stallTimeout to end with this line:
       If value is set to -1, the streaming job will not be terminated due to stream stall and 
       no attempt will be made to re-connect to the stream.
But, wouldn't we want to provide this alternative?
       the streaming job will not be terminated due to stream stall and 
       openmpf will attempt to re-connect to the stream.
I recall from an earlier discussion that we would want to support these two different behaviors for Live streams vs. video on Demand streams. Wouldn't having a separate parameter like attemptReconnectAtStall be better - that way we could describe in the API how re-connections are handled by Live streams vs. video on Demand streams, so the user could make a sensible choice for re-connect?

**Comment by brosenberg42** [comment]
@jrobble  wrote:
> if the value is -1, in additional to never terminating due to a stall, we will not try to reconnect to the stream.

This is not correct. The stall timeout specifies how long it will attempt to reconnect. If we do not reconnect, then we have to exit due to a stall.

When stall timeout is negative, that means that it will attempt to reconnect forever and will never exit due to a stall. When stall timeout is 0, that means that it will not reconnect and will exit due to a stall.

@dpierce17 wrote:
> "the streaming job will not be terminated due to stream stall and
openmpf will attempt to re-connect to the stream."

That is what is supposed to happen when the value is any negative number.

**Comment by dpierce17** [comment]
Ok, should we include any best practice information? In that earlier discussion it was mentioned that we would want to support these two different behaviors for Live streams vs. video on Demand streams. I don't recall which behavior was preferred for Live streams vs. video on Demand streams, but it would be helpful to include best practice in the REST API

**Comment by dpierce17** [comment]
When stall timeout is negative, that means that it will attempt to reconnect forever and will never exit due to a stall. When stall timeout is 0, that means that it will not reconnect and will exit due to a stall. If stalled, then best practice would be to set stallTimeout=0 for Video on Demand, and stallTimeout negative for Live Streams

**Comment by dpierce17** [comment]
When stall timeout is negative, that means that it will attempt to reconnect forever and will never terminate due to a stall. When stall timeout is 0, that means that it will immediately terminate when a frame can't be read. When stallTimeout is positive, that means the system will attempt to reconnect for that stall period. If connecting to a video on demand stream, set stallTimeout to 0. If connecting to a live stream, any value of stallTimeout would be valid.

**Comment by dpierce17** [comment]
When stall timeout is negative, that means that it will attempt to reconnect forever and will never terminate due to a stall. When stall timeout is 0, that means that it will immediately terminate when a frame can't be read. When stallTimeout is positive, that means the system will attempt to reconnect for that timeout period.  If connecting to a video on demand stream, set stallTimeout to 0. If connecting to a live stream, any value of stallTimeout would be valid.

**Comment by dpierce17** [comment]
Landed with D2392
