### ISSUE TITLE
Swagger documentation has “streamUri” listed twice

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#524]
The swagger documentation has the “streamUri” listed twice:

{
  "algorithmProperties": {},
  "enableOutputToDisk": true,
  "externalId": "string",
  "healthReportCallbackUri": "string",
  "jobProperties": {},
  "mediaProperties": {},
  "pipelineName": "string",
  "priority": 0,
  "segmentSize": 0,
  "stallTimeout": 0,
  "stream": {
    "mediaProperties": {},
    "segmentSize": 0,
    "streamUri": "string",
    "validStreamData": true
  },
  "streamUri": "string",
  "summaryReportCallbackUri": "string",
  "validRequest": true
}

It should only be listed once within the "stream" element.

**Comment by dpierce17** [comment]
This fix required an version update of SpringFox swagger from 2.1.1 to 2.6.1 to allow for usage of the @ApiModelProperty hidden attribute. The hidden attribute was supported starting in SpringFox 2.6. Note that a comment in OpenMPF pom.xml said that SpringFox swagger has to stay at version 2.1.1 to avoid a bug that was not supposed to be fixed until SpringFox swagger 2.3. According to the the release notes at https://github.com/springfox/springfox/blob/master/docs/release-notes.md, bug #951 was fixed in SpringFox 2.3. Added a TODO in pom.xml to indicate that the bug #95 fix needs to be verified, but the procedure for verifying the bug fix needs to be defined.  Note that the upgrade to SpringFox 2.6.1 required that spring-framework and joda-time versions also be updated due to dependencies.

**Comment by dpierce17** [comment]
Revised to not use @apimodelproperty hidden attribute to avoid requirement to upgrade software.

**Comment by dpierce17** [comment]
Landed with PR532
