### ISSUE TITLE
Investigate Tika script detection

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#875]
We need a way to compare two OCR'd outputs to see which one is more meaningful. Investigate Tika script detection by running some tests with gibberish to see it can be used to distinguish between garbage output (valid script characters that don't form meaningful words) and more useful output. Compare to Tesseract script detection.

**Comment by lmtoothman** [comment]
I think we will still need the Tesseract OSD no matter what since it happens before OCR. The Tika script detection would potentially be used after OCR to compare the two outputs.

**Comment by hhuangMITRE** [comment]
Right now, Tika's script detection is not designed for gibberish filtering. Submitting gibberish text oftentimes result in unexpected languages being predicted instead, even when the language prediction is set to only allow reasonably certain outputs. 

Since language detection uses N-gram matching, the component can be used to filter high density gibberish text under a few languages (ex. lorem ipsum text using Latin characters will be detected as gibberish). However this creates an issue if we compared OCR results of different lengths. A short string of gibberish might be recognized as a valid language with greater confidence than a longer, noisy input. 

Documentation for the language detection module (https://github.com/optimaize/language-detector) also suggests that it was not designed for low-quality text inputs. As a result we'll close this investigation for now unless Tika's language processing module is updated.
