### ISSUE TITLE
Investigate improving Tesseract performance

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#886]
Some ideas worth investigating:

- Processing one or more pages of a PDF at the same time in separate threads.
  - Consider adding support for a job property so that the user can set the number of pages.
  - As mentioned [here](https://github.com/tesseract-ocr/tesseract/issues/1600#issuecomment-393917656): "I would simply split the document/image into multiple files and use GNU Parallel to run multiple instances of tesseract with multithreading disabled."

- Experiment with setting OMP_THREAD_LIMIT.
   - From above link: "Tesseract 4 also uses up to four CPU threads while processing a page, so it will be faster than Tesseract 3 for a single page ... Set the maximum number of threads using the environment variable OMP_THREAD_LIMIT"
   - From @hhuangMITRE: "It seems like setting OPM_THREAD_LIMIT accelerates serial image processing, Tesseract might be running the images one after another rather than running on separate images at once"

Note that GPU support is limited and very experimental. It's not recommended for prime-time. From [here](https://github.com/tesseract-ocr/tesseract/wiki/TesseractOpenCL#how-to-build-tesseract-with-opencl): "OpenCL support in Tesseract is still considered experimental. There are some major bugs associated with it (see issue 837). Building Tesseract with OpenCL support is not recommended (for any version of Tesseract), unless you are a developer and want to improve the OpenCL code."

**Comment by voodookoop** [comment]
Some might want to know from where the magic "up to **four** CPU threads" came from. I think that the answer is in https://github.com/tesseract-ocr/tesseract/blob/master/src/lstm/lstm.cpp where you might see that the 4 thread parallelly does a kind of matrix-vector product calculation for 

- Cell inputs
- Gates inputs
- 2-D forget gates
- Output gates

parallelly. That's why it is maxed in 4 currently, since for example the Forward propagation in LSTM is done sequentially, but these 4 operation can be done parallely within a fwd prop. However the majority of the CPU resource in recognition stage is taken by one method (as per my CPU performance profiling done with Very Sleepy profiler on Windows): https://github.com/tesseract-ocr/tesseract/blob/master/src/arch/intsimdmatrixsse.cpp **IntDotProductSSE** method that is called (mostly) from MatrixDotVector method of LSTM fwd prop step, obviously only in case if the machine architecture supports, e.g. the CPU has SSE 4.1 feature. This is the SSE-optimized version of the **base method implementation** (can be found in intsimdmatrix.cpp). I highlight base implementation here because one can understand the most time-consuming task from there compared to the already-optimized SSE or AVX version implementation.

So matrix-vector multiplication. Knowing, that GPUs are very good at this tasks, especially on big matrices (which is unfortunately not the case here, we are talking about many, but smaller matrices), I think it still would worth a shot to see how lstm.cpp and belongings could be transformed to utilize for example CUBLAS **cublasSgemv** method that is specifically designed to do matrix-vector multiplication on GPU. There are problems though. One should move memory regions between the host-device (and it is bad for performance to do frequently), it would be CUDA/CUBLAS specific, hence not vendor-independent, will hardly be available on Android and some other drawbacks. I still think it would worth.

**Comment by jrobble** [comment]
Hi @voodookoop! Thanks for reaching out. I'm afraid that the title of this issue is misleading. By "Tesseract" we're referring to our Tesseract component, not the Tesseract framework itself. We're still in the process of evaluating the framework and trying to make the best use out of what's currently available to improve the performance of our compoennt. We appreciate your insights, but we don't intend to get involved in improving the Tesseract matrix mathematics at this time.

**Comment by jrobble** [comment]
Resolved by implementing support for processing multiple languages in parallel for images, and multiple pages in parallel for PDFs. No GPU support at this time.
