### ISSUE TITLE
Pre-crop frame before rotating and cropping to region

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#896]
Currently, the frame transformer utilities will rotate an entire frame before cropping it to a specified region. This may not be optimal. We should investigate if cropping the frame to a minimal region before rotation (and then performing cropping again for angles other than 90, 180, and 270 degrees) provides any performance benefit.

**Comment by jrobble** [comment]
Discussion of handling arbitrary rotation angles:

> Jeff: Naively, I thought of the problem as “find the center point, rotate around the center point, then draw the lines and cut.” Also, to do things optimally, you probably don’t want to rotate the whole image, you want to find the minimal region to rotate before making the cut.

> Brian: I do rotate the whole image.

> Jeff: Does that have a performance impact? Maybe the matrix math is not something to worry about.

> Brian: There isn't a way to just rotate the exact region you need. To avoid rotating the entire image you need to crop the bounding diamond, rotate, then crop again.

> Jeff: That seems to be what I had in mind.

> Brian: To do it that way, when you rotate the entire image, you need to make it bigger first. Then you need to rotate the bigger image.

> Jeff: Yeah, that makes sense. I’m not saying that what I had in mind is the best approach. It's just what made the most sense to me. I’m not asking you to change anything you're doing if you have confidence in your approach. I’m sure there are many wants to do this.

> Brian: Also, in the current code we don’t make that optimization. We rotate, then crop.

>Jeff: That’s a good point.

> Brian: warpAffine also runs on multiple threads automatically, so that will help with performance.

**Comment by brosenberg42** [comment]
[`cv::warpAffine`](https://docs.opencv.org/3.3.0/da/d54/group__imgproc__transform.html#ga0203d9ee5fcd28d40dbc4a1ea4451983) has a `cv::Size dsize` parameter. At first, I thought that OpenCV wouldn't be able to only map the points that end up in region specified by the dsize parameter since we don't know ahead of time which points will end up inside the specified region. 
The "Detailed Description" section from the ["Geometric Image Transformations"](https://docs.opencv.org/3.3.0/da/d54/group__imgproc__transform.html) page says:

>  In fact, to avoid sampling artifacts, the mapping is done in the reverse order, from destination to the source. That is, for each pixel (x,y) of the destination image, the functions compute coordinates of the corresponding "donor" pixel in the source image and copy the pixel value

This led me to believe that you could only do the mapping for the points that lie inside the region without mapping all of them. After stepping through the `cv::warpAffine` code I found that OpenCV is in fact only doing the mapping for the pixels in the specified region.

The destination matrix is created with the size specified by `dsize` [here](https://github.com/opencv/opencv/blob/3.3.0/modules/imgproc/src/imgwarp.cpp#L5878). `hal::warpAffine` is called [here](https://github.com/opencv/opencv/blob/3.3.0/modules/imgproc/src/imgwarp.cpp#L5968) and the destination matrix size is passed in. A Range is constructed [here](https://github.com/opencv/opencv/blob/3.3.0/modules/imgproc/src/imgwarp.cpp#L5847) using the size of the destination image. The `WarpAffineInvoker` is called here [here](https://github.com/opencv/opencv/blob/3.3.0/modules/imgproc/src/imgwarp.cpp#L5851). It loops over the pixels in the destination image [here](https://github.com/opencv/opencv/blob/3.3.0/modules/imgproc/src/imgwarp.cpp#L5453). Since it is looping over the pixels in the destination image, rather than the the source image, it will never compute the mapping for pixels that lie outside of the destination image.
